version: '3.7'
services:
  web:
    build: .
    image: fastapitrain
    ports:
      - "8000:8000"
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'production'
    networks:
      - backend
    ports:
      - "5431:5432"
    volumes:
      - database-pg:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  database-pg: