"""update1

Revision ID: 866be3f3ffaa
Revises: ae8295163457
Create Date: 2023-12-02 18:27:29.812876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866be3f3ffaa'
down_revision: Union[str, None] = 'ae8295163457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', sa.Float(), nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('user', 'balance')
    # ### end Alembic commands ###
